version: "3.8"
services:
  web-01:
    build: .
    container_name: web-01
    expose:
      - "8000"
    networks:
      - webnet

  web-02:
    build: .
    container_name: web-02
    expose:
      - "8000"
    networks:
      - webnet

  lb-01:
    image: nginx:stable
    container_name: lb-01
    ports:
      - "8080:80"   # access LB on host:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-01
      - web-02
    networks:
      - webnet

networks:
  webnet:
